return {
  { -- Useful plugin to show you pending keybinds.
    'folke/which-key.nvim',
    event = 'VimEnter', -- Sets the loading event to 'VimEnter'
    config = function() -- This is the function that runs, AFTER loading
      require('which-key').setup()
      require('which-key').add {
        {
          mode = { 'n' },
          icon = ' ',
          group = 'system',
          { '<leader>r', desc = '[R]ename' },
          { '<leader>r_', hidden = true },
          { '<leader>s', desc = '[S]ource' },
          { '<leader>s_', hidden = true },
          { '<leader>c', desc = '[C]ode' },
          { '<leader>cf', desc = '[F]ormat' },
          { '<leader>d', desc = '[D]ocument' },
          { '<leader>d_', hidden = true },
          { '<leader>w', desc = '[W]orkspace/[W]iki' },
          { '<leader>Y', desc = '[Y]ank to system clipboard' },
          { '<leader>y', desc = '[Y]ank to system clipboard' },
          { '<leader>yy', desc = '[Y]ank to system clipboard' },

          { '<localleader>%', desc = '[T]mux Vertical split' },
          { '<localleader>"', desc = '[T]mux Horizontal split' },
          { '<localleader>d', desc = '[D]ebug' },
          { '<localleader>dc', desc = '[D]ebug [C]ontinue/Start' },
          { '<localleader>n', desc = '[N]otify' },
          { '<localleader>w', desc = '[W]iki' },
        },
        {
          mode = { 'n' },
          group = 'toggle',
          icon = ' ',
          { '<leader>t', desc = '[T]oggle' },
          { '<leader>tb', desc = '[B]lame line' },
          { '<leader>tD', desc = 'Toggle [D]eleted' },
        },
        {
          mode = { 'n' },
          group = 'find',
          icon = '󰭎 ',
          { '<leader>f', desc = '[F]ind' },
          { '<leader>f_', hidden = true },
          { '<leader>fg', desc = '[F]ind [G]it' },
          { '<leader>fl', desc = '[L]ive [G]rep' },
          { '<leader>ft', desc = '[T]hemes' },
        },
        {
          mode = { 'n' },
          group = 'git',
          icon = '󰊢 ',
          { '<leader>g', desc = '[G]it' },
          { '<leader>g_', hidden = true },
          { '<leader>gt', desc = '[T]oggle' },
          { '<leader>gc', desc = '[G]it [C]opilot'},
          { '<leader>gcm', desc = '[G]it [C]opilot [Message]' },
          { '<localleader>g', desc = '[G]it' },
          { '<localleader>g_', hidden = true },
        },
        {
          mode = { 'n' },
          group = 'harpoon',
          icon = '󰛢 ',
          { '<leader>h', desc = '[H]arpoon' },
          { '<leader>h_', hidden = true },
          { '<leader>hl', desc = '[L]ist Marks' },
          { '<leader>hn', desc = 'Navigate [N]ext' },
          { '<leader>ha', desc = '[A]dd to Harpoon' },
          { '<leader>h1', desc = 'Navigate file [1]' },
          { '<leader>h2', desc = 'Navigate file [2]' },
          { '<leader>h3', desc = 'Navigate file [3]' },
          { '<leader>h4', desc = 'Navigate file [4]' },
          { '<leader>h5', desc = 'Navigate file [5]' },
        },
        {
          mode = { 'n' },
          group = 'notes',
          icon = ' ',
          { '<localleader>o', desc = '[O]bsidian' },
          { '<localleader>o_', hidden = true },
          { '<localleader>oo', desc = '[O]bsidian [O]pen' },
          { '<localleader>on', desc = '[O]bsidian [N]ew' },
          { '<localleader>od', desc = '[O]bsidian [D]aily' },
          { '<localleader>ot', desc = '[O]bsidian [T]emplate' },
          { '<leader>w_', hidden = true },
          { '<leader>ww', desc = 'Vimwiki Index' },
        },
        {
          mode = { 'n' },
          group = 'trouble',
          { '<localleader>t', desc = '[T]rouble' },
          { '<localleader>t_', hidden = true },
        },
        {
          mode = { 'n' },
          group = 'undotree',
          { '<localleader>u', group = '[U]ndotree Toggle' },
          { '<localleader>u_', hidden = true },
        },
        {
          group = 'codesnap',
          icon = ' ',
          { '<localleader>c', mode = { 'x', 'n' }, desc = '[C]odesnap' },
          { '<localleader>cs', desc = '[C]odesnap [S]ave' },
          { '<localleader>cc', desc = '[C]odesnap [C]opy' },
        },
      }
    end,
  },
}
