# =================================================
# =========== Window Manager for Macos ============
# =================================================

after-login-command = []

# Use it to add commands that run after AeroSpace startup.
# 'after-startup-command' is run after 'after-login-command'
after-startup-command = [
    # JankyBorders has a built-in detection of already running process,
    # so it won't be run twice on AeroSpace restart
    'exec-and-forget borders active_color=0xffe1e3e4 inactive_color=0xff494d64 width=5.0'
]

# Start AeroSpace at login
start-at-login = true

# Normalizations. See: https://nikitabobko.github.io/AeroSpace/guide#normalization
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

# The 'accordion-padding' specifies the size of accordion padding
# Set 0 to disable the padding feature
accordion-padding = 30

# Possible values: tiles|accordion
default-root-container-layout = 'tiles'

# Possible values: horizontal|vertical|auto
# 'auto' means: wide monitor (anything wider than high) gets horizontal orientation,
#               tall monitor (anything higher than wide) gets vertical orientation
default-root-container-orientation = 'auto'

# Possible values: (qwerty|dvorak)
key-mapping.preset = 'qwerty'

# Mouse follows focus when focused monitor changes
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']
on-focus-changed = ['move-mouse window-lazy-center']

# Gaps between windows (inner-*) and between monitor edges (outer-*).
# Possible values:
# - Constant:     gaps.outer.top = 8
# - Per monitor:  gaps.outer.top = [{ monitor.main = 16 }, { monitor."some-pattern" = 32 }, 24]
#                 In this example, 24 is a default value when there is no match.
#                 Monitor pattern is the same as for 'workspace-to-monitor-force-assignment'.
#                 See: https://nikitabobko.github.io/AeroSpace/guide#assign-workspaces-to-monitors
[gaps]
inner.horizontal = 5
inner.vertical =   5
outer.left =       5
outer.bottom =     5
outer.top =        5
outer.right =      5

# 'main' binding mode declaration
# 'main' binding mode must be always presented
[mode.main.binding]

# All possible keys:
# - Letters.        a, b, c, ..., z
# - Numbers.        0, 1, 2, ..., 9
# - Keypad numbers. keypad0, keypad1, keypad2, ..., keypad9
# - F-keys.         f1, f2, ..., f20
# - Special keys.   minus, equal, period, comma, slash, backslash, quote, semicolon, backtick,
#                   leftSquareBracket, rightSquareBracket, space, enter, esc, backspace, tab
# - Keypad special. keypadClear, keypadDecimalMark, keypadDivide, keypadEnter, keypadEqual,
#                   keypadMinus, keypadMultiply, keypadPlus
# - Arrows.         left, down, up, right

# All possible modifiers: cmd, alt, ctrl, shift

# All possible commands: https://nikitabobko.github.io/AeroSpace/commands

# Uncomment this line to open up terminal with alt + enter shortcut
# alt-enter = 'exec-and-forget open -n /System/Applications/Utilities/Terminal.app'

# Change layout of windows
ctrl-alt-shift-slash = 'layout tiles horizontal vertical'
ctrl-alt-shift-comma = 'layout accordion horizontal vertical'

# Change focus between windows in a workspace
alt-h = 'focus left'
alt-j = 'focus down'
alt-k = 'focus up'
alt-l = 'focus right'

# Move the focused workspace
ctrl-alt-shift-cmd-h = 'move left'
ctrl-alt-shift-cmd-j = 'move down'
ctrl-alt-shift-cmd-k = 'move up'
ctrl-alt-shift-cmd-l = 'move right'

# Resizing and window manipulation
ctrl-alt-shift-minus = 'resize smart -50'
ctrl-alt-shift-equal = 'resize smart +50'
alt-m = 'fullscreen'

# Change to workspace
ctrl-alt-shift-cmd-1 = 'workspace 1'
ctrl-alt-shift-cmd-2 = 'workspace 2'
ctrl-alt-shift-cmd-3 = 'workspace 3'
ctrl-alt-shift-cmd-4 = 'workspace 4'
ctrl-alt-shift-cmd-5 = 'workspace 5'
ctrl-alt-shift-cmd-6 = 'workspace 6'
ctrl-alt-shift-cmd-7 = 'workspace 7'
ctrl-alt-shift-cmd-8 = 'workspace 8'
ctrl-alt-shift-cmd-9 = 'workspace 9'
ctrl-alt-shift-cmd-a = 'workspace A'
ctrl-alt-shift-cmd-b = 'workspace B'
ctrl-alt-shift-cmd-c = 'workspace C'
ctrl-alt-shift-cmd-d = 'workspace D'
ctrl-alt-shift-cmd-e = 'workspace E'
ctrl-alt-shift-cmd-f = 'workspace F'
ctrl-alt-shift-cmd-g = 'workspace G'
ctrl-alt-shift-cmd-i = 'workspace I'
ctrl-alt-shift-cmd-m = 'workspace M'
ctrl-alt-shift-cmd-n = 'workspace N'
ctrl-alt-shift-cmd-o = 'workspace O'
ctrl-alt-shift-cmd-p = 'workspace P'
ctrl-alt-shift-cmd-q = 'workspace Q'
ctrl-alt-shift-cmd-r = 'workspace R'
ctrl-alt-shift-cmd-s = 'workspace S'
ctrl-alt-shift-cmd-t = 'workspace T'
ctrl-alt-shift-cmd-u = 'workspace U'
ctrl-alt-shift-cmd-v = 'workspace V'
ctrl-alt-shift-cmd-w = 'workspace W'
ctrl-alt-shift-cmd-x = 'workspace X'
ctrl-alt-shift-cmd-y = 'workspace Y'
ctrl-alt-shift-cmd-z = 'workspace Z'

# Move focused window to workspace
ctrl-alt-shift-1 = 'move-node-to-workspace 1'
ctrl-alt-shift-2 = 'move-node-to-workspace 2'
ctrl-alt-shift-3 = 'move-node-to-workspace 3'
ctrl-alt-shift-4 = 'move-node-to-workspace 4'
ctrl-alt-shift-5 = 'move-node-to-workspace 5'
ctrl-alt-shift-6 = 'move-node-to-workspace 6'
ctrl-alt-shift-7 = 'move-node-to-workspace 7'
ctrl-alt-shift-8 = 'move-node-to-workspace 8'
ctrl-alt-shift-9 = 'move-node-to-workspace 9'
ctrl-alt-shift-a = 'move-node-to-workspace A'
ctrl-alt-shift-b = 'move-node-to-workspace B'
ctrl-alt-shift-c = 'move-node-to-workspace C'
ctrl-alt-shift-d = 'move-node-to-workspace D'
ctrl-alt-shift-e = 'move-node-to-workspace E'
ctrl-alt-shift-f = 'move-node-to-workspace F'
ctrl-alt-shift-g = 'move-node-to-workspace G'
ctrl-alt-shift-i = 'move-node-to-workspace I'
ctrl-alt-shift-m = 'move-node-to-workspace M'
ctrl-alt-shift-n = 'move-node-to-workspace N'
ctrl-alt-shift-o = 'move-node-to-workspace O'
ctrl-alt-shift-p = 'move-node-to-workspace P'
ctrl-alt-shift-q = 'move-node-to-workspace Q'
ctrl-alt-shift-r = 'move-node-to-workspace R'
ctrl-alt-shift-s = 'move-node-to-workspace S'
ctrl-alt-shift-t = 'move-node-to-workspace T'
ctrl-alt-shift-u = 'move-node-to-workspace U'
ctrl-alt-shift-v = 'move-node-to-workspace V'
ctrl-alt-shift-w = 'move-node-to-workspace W'
ctrl-alt-shift-x = 'move-node-to-workspace X'
ctrl-alt-shift-y = 'move-node-to-workspace Y'
ctrl-alt-shift-z = 'move-node-to-workspace Z'

# Switch back and forth between workspaces
alt-tab = 'workspace-back-and-forth'

# Switch workspace to different montiors
ctrl-alt-shift-tab = 'move-workspace-to-monitor --wrap-around next'

# Toggle Service mode on
ctrl-alt-shift-semicolon = 'mode service'

# 'service' binding mode declaration.
[mode.service.binding]
esc = ['reload-config', 'mode main']
r = ['flatten-workspace-tree', 'mode main'] # reset layout
#s = ['layout sticky tiling', 'mode main'] # sticky is not yet supported https://github.com/nikitabobko/AeroSpace/issues/2
t = ['layout floating tiling', 'mode main'] # Toggle between floating and tiling layout
# Turn off aerospace
q = ['enable toggle']
backspace = ['close-all-windows-but-current', 'mode main']

alt-shift-h = ['join-with left', 'mode main']
alt-shift-j = ['join-with down', 'mode main']
alt-shift-k = ['join-with up', 'mode main']
alt-shift-l = ['join-with right', 'mode main']

# Custom preference for specific applicataion

# If opened application is a terminal => move to workspace T
[[on-window-detected]]
if.app-id='com.github.wez.wezterm'
run = "move-node-to-workspace T"

[[on-window-detected]]
# If opened application is notes => move to workspace N]
if.app-id='com.apple.Notes'
run = "move-node-to-workspace N"

# If opened application is browser => move to workspace B]
[[on-window-detected]]
if.app-id='company.thebrowser.Browser'
run = "move-node-to-workspace B"

# If opened application is postman => move to workspace P]
[[on-window-detected]]
if.app-id='com.postmanlabs.mac'
run = "move-node-to-workspace P"

# If opened application is finder => move to workspace F]
[[on-window-detected]]
if.app-id='com.apple.finder'
run = "move-node-to-workspace F"

# If opened application is Excel => move to workspace F]
[[on-window-detected]]
if.app-id='com.microsoft.Excel'
run = "move-node-to-workspace E"
