format = """
[](#d3869b)\
$os\
$username\
[](bg:#fb4934 fg:#d3869b)\
$directory\
[](fg:#fb4934 bg:#d79921)\
$git_branch\
$git_status\
[](fg:#d79921 bg:#83a598)\
$c\
$php\
$elixir\
$elm\
$golang\
$gradle\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
$scala\
[](fg:#83a598 bg:#458588)\
$docker_context\
[](fg:#458588 bg:#33658A)\
$time\
[](fg:#33658A)\
"""

# Disable the blank line at the start of the prompt
# add_newline = false

# You can also replace your username with a neat symbol like   or disable this
# and use the os module below
[username]
# symbol = " "
show_always = true
style_user = "bg:#d3869b"
style_root = "bg:#d3869b"
format = '[$user ]($style)'
disabled = false

# An alternative to the username module which displays a symbol that
# represents the current operating system
[os]
style = "bg:#d3869b"
disabled = true # Disabled by default

[directory]
style = "bg:#fb4934"
format = "[ $path ]($style)"
truncation_length = 10
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
"AWL" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = " 󰈙 "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important 󰈙 " = " 󰈙 "

[c]
symbol = " "
style = "bg:#83a598"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = " "
style = "bg:#458588"
format = '[ $symbol ($context) ($path) ]($style)'

[elixir]
symbol = " "
style = "bg:#83a598"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = " "
style = "bg:#83a598"
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = ""
style = "bg:#d79921"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#d79921"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = " "
style = "bg:#83a598"
format = '[ $symbol ($version) ]($style)'

[php]
symbol = " "
style = "bg:#83a598"
format = '[ $symbol ($version) ]($style)'

[gradle]
style = "bg:#83a598"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = " "
style = "bg:#83a598"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "bg:#83a598"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = " "
style = "bg:#83a598"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:#83a598"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = "󰆥 "
style = "bg:#83a598"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "bg:#83a598"
format = '[ $symbol ($version) ]($style)'

[scala]
symbol = " "
style = "bg:#83a598"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#33658A"
format = '[ 󰚭 $time ]($style)'
