[env]
TERM = "xterm-256color"

[window]
padding = { x = 5, y = 5 }
decorations = "Buttonless"
opacity = 0.75
blur = true
option_as_alt = "Both"

[font]
size = 14
normal = { family = "Hack Nerd Font Mono", style = "Regular"}
bold = { family = "Hack Nerd Font Mono", style = "Bold"}
italic = { family = "Hack Nerd Font Mono", style = "Italic"}
bold_italic = { family = "Hack Nerd Font Mono", style = "Bold Italic"}

[colors]
primary = { background = '0x282828', foreground = '0xdfbf8e' }
normal = { black = '0x665c54', red = '0xea6962', green = '0xa9b665', yellow = '0xe78a4e', blue = '0x7daea3', magenta = '0xd3869b', cyan = '0x89b482', white = '0xdfbf8e' }
bright = { black = '0x928374', red= '0xea6962', green= '0xa9b665', yellow= '0xe3a84e', blue= '0x7daea3', magenta= '0xd3869b', cyan= '0x89b482', white= '0xdfbf8e' }

[cursor]
style = { shape = "Block", blinking = "Never" }

[mouse]
hide_when_typing = true
