import = [
  "~/.config/alacritty/dark.toml"
]

live_config_reload = true

[env]
TERM = "xterm-256color"

[window]
padding = { x = 5, y = 5 }
decorations = "Buttonless"
opacity = 0.75
blur = true
option_as_alt = "Both"
dynamic_title = true

[font]
size = 14
normal = { family = "Hack Nerd Font Mono", style = "Regular"}
bold = { family = "Hack Nerd Font Mono", style = "Bold"}
italic = { family = "Hack Nerd Font Mono", style = "Italic"}
bold_italic = { family = "Hack Nerd Font Mono", style = "Bold Italic"}

[cursor]
style = { shape = "Block", blinking = "Never" }

[mouse]
hide_when_typing = true

[[keyboard.bindings]]
action = "CreateNewWindow"
key = "Return"
mods = "Control|Shift"

[[keyboard.bindings]]
key = "/"
action = "SearchForward"
mode = "Vi|~Search"
mods = "Shift"
